FROM intel-oneapi-hpckit-dev:ubuntu20

ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

RUN apt-get update -y && \
apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
        build-essential \
        ca-certificates \
        curl \
        git \
        gnupg \
        libexpat1-dev \
        libssl-dev \
        m4 \
        pkg-config \
        python \
        vim \
        wget \
        --

ENV I_MPI_THREAD_SPLIT=1
ENV I_MPI_LIBRARY_KIND='release_mt'

RUN cd /tmp && \
    curl -f -s -S -R -L -O https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.tar.gz && \
    mkdir -p /home/builder/cmake && \
    tar zxf cmake-3.16.4-Linux-x86_64.tar.gz -C /home/builder/cmake --strip-components=1 && \
    rm cmake-3.16.4-Linux-x86_64.tar.gz && \
    echo export PATH=/home/builder/cmake/bin:\$PATH >> /etc/bashrc

RUN git clone https://github.com/slawrence87544/hpc-stack.git && \
    cd hpc-stack && \
    git checkout feature/add-ufs-s2s-support && \
    ./build_stack.sh -p /home/builder -c config/config_linux_ubuntu20_intel_oneapi_beta09.sh -y config/stack_ufs_s2s_model.yaml

RUN echo 'export PATH=/home/builder/bin:$PATH'      >> /etc/bash.bashrc && \
    echo 'export LD_LIBRARY_PATH=/home/builder/lib:$LD_LIBRARY_PATH' >> /etc/bash.bashrc && \
    echo 'export CMAKE_PREFIX_PATH=/home/builder'   >> /etc/bash.bashrc && \
    echo 'export FC=mpiifort' >> /etc/bash.bashrc && \
    echo 'export CC=mpiicc'   >> /etc/bash.bashrc && \
    echo 'export CXX=mpiicpc' >> /etc/bash.bashrc

WORKDIR /home/builder
