FROM intel-oneapi-hpc-stack:ubuntu20

SHELL ["/bin/bash", "-c"]

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh && \
    ln -s /usr/bin/make /usr/bin/gmake

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
        csh \
        doxygen \
        emacs \
        git-flow \
        graphviz \
        ksh \
        lynx \
        nedit \
        texinfo \
        texlive-latex-recommended \
        tcsh \
        zsh && \
    rm -rf /var/lib/apt/lists/*

ENV CMAKE_C_COMPILER=mpiicc \
    CMAKE_CXX_COMPILER=mpiicpc \
    CMAKE_Fortran_COMPILER=mpiifort \
    CMAKE_Platform=linux.intel \
    CMAKE_PREFIX_PATH=/home/builder \
    ESMFMKFILE=/home/builder/lib/esmf.mk \
    NETCDF=/home/builder \
    CMAKE_FLAGS="-DOPENMP=OFF -DPARALLEL_NETCDF=ON -DS2S=ON -DAVX2=OFF" \
    CCPP_SUITES="FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled"

RUN cd /home/builder && git clone https://github.com/ufs-community/ufs-weather-model.git && \
    cd /home/builder/ufs-weather-model && \
    git submodule update --recursive --init && \
    ./build.sh
