cmake:
  build: NO
  version: 3.17.2

jpeg:
  build: NO
  version: 9.1.0

zlib:
  build: YES
  shared: NO
  version: 1.2.11

png:
  build: YES
  shared: NO
  version: 1.6.35

szip:
  build: YES
  shared: NO
  version: 2.1.1

jasper:
  build: YES
  shared: NO
  version: 2.0.15

udunits:
  build: YES
  shared: NO
  version: 2.2.26

hdf5:
  build: YES
  version: 1.10.6
  shared: NO
  enable_szip: NO
  enable_zlib: YES

pnetcdf:
  build: NO
  version: 1.12.1
  shared: NO

netcdf:
  build: YES
  shared: NO
  enable_pnetcdf: NO
  version_c: 4.7.4
  version_f: 4.5.3
  version_cxx: 4.3.1

nccmp:
  build: YES
  version: 1.8.7.0

nco:
  build: NO
  version: 4.9.3

pio:
  build: YES
  version: 2.5.1
  enable_pnetcdf: NO
  enable_gptl: NO

esmf:
  build: YES
  version: 8_1_0_beta_snapshot_21
  shared: NO
  enable_pnetcdf: NO
  debug: NO

gptl:
  build: NO
  version: 8.0.2

fftw:
  build: NO
  version: 3.3.8

tau2:
  build: NO
  version: 3.25.1

bacio:
  build: YES
  version: v2.4.1
  install_as: 2.4.1

sigio:
  build: YES
  version: v2.3.2
  install_as: 2.3.2

sfcio:
  build: YES
  version: v1.4.1
  install_as: 1.4.1

gfsio:
  build: YES
  version: v1.4.1
  install_as: 1.4.1

w3nco:
  build: YES
  version: v2.4.1
  install_as: 2.4.1

sp:
  build: YES
  version: v2.3.1
  install_as: 2.3.1
  openmp: OFF

ip:
  build: YES
  version: v3.3.1
  install_as: 3.3.1
  openmp: OFF

ip2:
  build: NO
  version: v1.1.1
  install_as: 1.1.1
  openmp: OFF

landsfcutil:
  build: YES
  version: v2.4.1
  install_as: 2.4.1
  openmp: OFF

nemsio:
  build: YES
  version: v2.5.2
  install_as: 2.5.2

nemsiogfs:
  build: YES
  version: v2.5.1
  install_as: 2.5.1
  openmp: OFF

w3emc:
  build: YES
  version: v2.7.1
  install_as: 2.7.1

g2:
  build: YES
  version: v3.4.1
  install_as: 3.4.1

g2tmpl:
  build: YES
  version: v1.9.1
  install_as: 1.9.1

crtm:
  build: YES
  version: v2.3.0
  install_as: 2.3.0

nceppost:
  build: YES
  version: dceca26
  install_as: dceca26
  openmp: OFF

wrf_io:
  build: YES
  version: v1.1.1-cmake-v2
  install_as: 1.1.1
  openmp: OFF

bufr:
  build: YES
  version: bufr_v11.4.0
  install_as: 11.4.0

wgrib2:
  build: YES
  version: v2.0.8-cmake-v1.0.3
  install_as: 2.0.8
  openmp: OFF
  spectral: OFF
  ipolates: 0

prod_util:
  build: YES
  version: develop
  install_as: develop

grib_util:
  build: YES
  version: develop
  install_as: develop
  openmp: OFF
