name: Build Linux OpenMPI
on: [push, pull_request]

jobs:
  build:
    name: linux-openmpi
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9
      FC: gfortran-9
      VERBOSE: 1

    steps:

    - name: install-openmpi
      run: |
        sudo apt-get install openmpi-bin libopenmpi-dev

    - name: checkout-linux-openmpi
      uses: actions/checkout@v2
      with:
        path: linux-openmpi
        submodules: true

    - name: build-linux-openmpi
      run: |
        cd linux-openmpi
        export CC=mpicc
        export CXX=mpicxx
        export FC=mpifort
        ./build_stack.sh -p $GITHUB_WORKSPACE/linux-openmpi/install -c config/config_custom.sh -y config/stack_custom.yaml 2>&1 | tee build-linux-openmpi.log

    - name: upload-build-linux-openmpi-log
      uses: actions/upload-artifact@v2
      with:
        name: build-linux-openmpi-log
        path: build-linux-openmpi.log
