name: Build Linux OpenMPI
on: [push, pull_request]

jobs:
  build:
    name: linux-openmpi
    runs-on: ubuntu-latest
    env:
      FC: gfortran-9
      CC: gcc-9
      CXX: g++-9
      VERBOSE: 1

    steps:

    - name: install-openmpi
      run: |
        sudo apt-get install openmpi-bin libopenmpi-dev

    - name: checkout-linux-openmpi
      uses: actions/checkout@v2
      with:
        path: linux-openmpi
        submodules: true

    - name: build-linux-openmpi
      run: |
        cd linux-openmpi
        build_stack.sh -p ./install -c config/config_custom.sh -y config/stack_custom.yaml
