name: Build Ubuntu
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    env:
      VERBOSE: 1
    runs-on: ubuntu-20.04

    steps:

    - name: Get sources
      uses: actions/checkout@v2
      with:
        path: hpc-stack

    - name: Test DOWNLOAD_ONLY
      run: |
        cd hpc-stack
        sed -i "s/DOWNLOAD_ONLY=N/DOWNLOAD_ONLY=Y/" ./config/config_custom.sh
        prefix=$GITHUB_WORKSPACE/install
        gnu_ver=$( gcc -dumpfullversion -dumpversion )
        python_ver=$( python3 --version | cut -d " " -f2 | cut -d. -f1-2 )
        export HPC_COMPILER="gnu/${gnu_ver}"
        export HPC_MPI="${{ matrix.mpi }}/${mpi_ver}"
        export HPC_PYTHON="python/${python_ver}"
        ./build_stack.sh -p $prefix -c config/config_custom.sh -y stack/stack_noaa.yaml
